tap "oven-sh/bun", trusted: true
brew "fd"
brew "fzf"
brew "go"
brew "lazygit"
brew "neovim"
brew "podman"
brew "ripgrep"
brew "rustup"
brew "tailscale"
brew "tealdeer"
brew "tree-sitter-cli"
brew "typst"
brew "uv"
brew "yazi"
brew "oven-sh/bun/bun"
cask "ghostty"
cask "helium-browser"
cask "raycast"
cask "spotify"
# cargo "tdf-viewer"
