[mgr]
show_hidden = false
show_preview = false
linemode = "none"
sort_dir_first = true
ratio = [0, 4, 0]

[opener]
pdf = [{ run = 'tdf "$@" -m 1 -f true', block = true, for = "unix" }]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]

[open]
rules = [{ name = "*.pdf", use = "pdf" }, { name = "*", use = "edit" }]
