[mgr]
show_hidden = false
show_preview = false
linemode = "none"
sort_dir_first = true
ratio = [0, 4, 0]

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
pdf = [
    { run = 'tdf "$@"', block = true, for = "unix" }
]

[open]
rules = [
    { name = "*.typ", use = "edit" },
    { name = "*.pdf", use = "pdf" },
]

